[package]
name = "aleo-prover"
version = "0.5.1"
edition = "2021"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# for appimage
[[bin]]
name = "aleo-prover"
path = "src/main.rs"

[dependencies]
snarkvm = { path = "../snarkVM" }
snarkvm-algorithms = { path = "../snarkVM/algorithms" }
# snarkos-account = { path = "../snarkOS/account"}
# snarkos-node-messages = { path = "../snarkOS/node/messages"}
snarkos-account = { git = "https://github.com/aleohq/snarkOS.git", branch = "feat/initial-gpu-prover" }
snarkos-node-messages = { git = "https://github.com/aleohq/snarkOS.git", branch = "feat/initial-gpu-prover" }
rand = "0.8.5"
num_cpus = "1.14.0"
rayon = "1.6.0"
anyhow = "1.0.66"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
tokio-stream = "0.1.11"
futures = "0.3.25"
futures-util = "0.3.25"
crossbeam = "0.8.2"
bytes = "1.3.0"
bincode = "1.3.3"
byteorder = "1.4.3"
ansi_term = "0.12.1"
json-rpc-types = "1.2.0"
hex = "0.4.3"
dotenvy = "0.15.6"

[dependencies.clap]
version = "4.0.28"
features = ["derive"]

[dependencies.tokio]
version = "1.22.0"
features = [
    "rt-multi-thread",
    "macros",
    "sync",
    "net"
]

[dependencies.tokio-util]
version = "0.7.4"
features = ["codec"]

[dependencies.serde_json]
version = "1.0.89"
features = ["preserve_order"]

[features]
cuda = ["snarkvm/cuda"]

[profile.dev]
opt-level = 1
debug-assertions = false

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[package.metadata.appimage]
auto_link = true
auto_link_exclude_list = [
    "libc.so*",
    "libdl.so*",
    "libpthread.so*",
]
